sudo: false
dist: xenial

language: php
jobs:
  include:
    - php: "5.6"
      env: COMPOSER=composer-v5.json
    - php: "7.4"
      env: COMPOSER=composer-v5.json
    - php: "8.0"
      env: COMPOSER=composer.json

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
    - $HOME/.cache/yarn

services:
  - mysql

env:
  global:
    - APP_DEBUG=true
    - DB_HOST=localhost
    - DB_DATABASE=sklep_sms_test
    - DB_USERNAME=root
    - DB_PASSWORD=

before_install:
  - nvm install stable
  - mysql -e 'CREATE DATABASE sklep_sms_test;'

install:
  - pip install pre-commit
  - composer self-update --1
  - composer install --no-interaction
  - composer dump
  - yarn install

script:
  - pre-commit run --all-files -c .pre-commit-config-ci.yaml
  - PHP_VERSION=$(php -v | grep ^PHP | cut -d' ' -f2)
  - |
    docker run \
    --rm \
    --env PHP_VERSION=$PHP_VERSION \
    -v $(pwd):/project \
    rector/rector:latest \
    process \
    --config rector.php \
    --output-file=rector_output.txt \
    --output-format=json
  - php artisan test:setup
  - NODE_ENV=production yarn build
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls

before_deploy:
  - rm -Rf vendor
  - composer install --no-dev --no-interaction --prefer-dist
  - BUILD_NAME="build-${PHP_VERSION}.zip"
  - pre-commit run --all-files
  - |
    zip -r \
    --exclude='data/cache/**' \
    --exclude='data/errors/**' \
    --exclude='data/transactions/**' \
    ${BUILD_NAME} \
    build/ \
    bootstrap/ \
    confidential/ \
    data/ \
    includes/ \
    migrations/ \
    translations/ \
    themes/ \
    vendor/ \
    .htaccess \
    favicon.png \
    index.php \
    README.md

deploy:
  provider: releases
  api_key:
    secure: Ytqd1sJIIC1aVQjY/8TWggsNMr6s/52CpUaH8HppLe96+dVg74zvO4lAOITO8MP74oRe/DJ0U6eqV2oV0Ypsj6tHXXC9yMzi1v0TiKkJJKz5NhYiHxLraPWWz8vbCjso0tEgvBX4rcB+nuDQ5Afj+5F3mwTp32VhWl4V8ln5piYip9kUl9GChh8+5CG9/b1BXBTZWnPkuD+2UOo43nQ9XMmH2vPp+otT3nuR09lDA2W3arbwyWWSMk60fvYHlxMkK5rKE78KmAtbncEeFNsdIXTZXMvp43RU3Ap59LKqkhCz4aM7HrjRe82MQwTuhsVR151TyhBB93wEX0jPW8UFwpsP5vKB3wmqPbQzo2USlNOq2WIP2iaTEuNAfRdTy5+WPp14ba4poeYsMKs+Fc28nd3f/IoJglq75oW7LwgMQQnnS5Wcjw+y4nQ/CVO3fuTegMUJ5RPx6PEloXgQvkX2oHexdQ0xQv595rfQoBfCHt/i+BHRq2yok69sD3XO3mOXywqa/LZLC5wXAV6CzBY6IUcqfgWf7yVOngS6TIn7uiJaTsJkV5ZkH/m8DsQaGZzt2u10uF68NwsxIKavIyvkmCwX4WYB4aswvQ6Mj5VPz2cOwY9H9KqIGKh+pG3sZvjcB1M9CKEgQ4Thwr2KPltVkMcfG8Vnq0w9UnOERX87XNA=
  file: "${BUILD_NAME}"
  skip_cleanup: true
  on:
    tags: true
    php:
      - '5.6'
      - '8.0'
